### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by langyazhouwl** [AlexZhuo/AlxGifHelper#1]
Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6419)
                                                                       at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:911)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.widget.ScrollView.requestLayout(ScrollView.java:1483)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:361)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:361)
                                                                       at android.view.View.requestLayout(View.java:17490)
                                                                       at android.widget.TextView.checkForRelayout(TextView.java:6881)
                                                                       at android.widget.TextView.setText(TextView.java:4067)
                                                                       at android.widget.TextView.setText(TextView.java:3925)
                                                                       at android.widget.TextView.setText(TextView.java:3900)
                                                                       at com.stay.engine.AlxGifHelper$1.onStart(AlxGifHelper.java:106)
                                                                       at com.stay.engine.AlxGifHelper$2.doInBackground(AlxGifHelper.java:257)
                                                                       at com.stay.engine.AlxGifHelper$2.doInBackground(AlxGifHelper.java:253)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by langyazhouwl** [comment]
在doInBackground的onstart方法写了设置UI代码，应该是这个问题
