### ISSUE TITLE
依赖realm出现这个错误 改怎么解决

### ISSUE THREAD

**Issue by drrino** [AlexZhuo/AlxGifHelper#2]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.grtech.yousports/app_lib/libpl_droidsonroids_gif.so1.2.6" is 32-bit instead of 64-bit
                                                                          at java.lang.Runtime.load(Runtime.java:332)
                                                                          at java.lang.System.load(System.java:1069)
                                                                          at pl.droidsonroids.gif.ReLinker.loadLibrary(ReLinker.java:59)
                                                                          at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
                                                                          at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:21)
                                                                          at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:124)
                                                                          at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:135)
                                                                          at com.grtech.yousports.widget.gif.AlxGifHelper.displayImage(AlxGifHelper.java:179)
                                                                          at com.grtech.yousports.widget.gif.AlxGifHelper.displayImage(AlxGifHelper.java:67)
                                                                          at com.grtech.yousports.ui.homepage2.HomeFragment2$3.getView(HomeFragment2.java:124)
                                                                          at com.grtech.yousports.widget.HomeADPager$MAdapter.instantiateItem(HomeADPager.java:103)
                                                                          at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1006)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1154)

**Comment by AlexZhuo** [comment]
修改/libraries/android-gif-drawable/src/main/jni/Application.mk
这个文件，加入64位CPU的编译
